# Generated by Django 4.2.23 on 2025-06-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='decripcion',
            new_name='descripcion',
        ),
    ]
